#!/usr/bin/env python3
"""Build the dependency-free static site from Julia-generated SVG artifacts."""

from __future__ import annotations

import html
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = Path(__file__).resolve().parent
SOURCE = ROOT / "julia" / "artifacts" / "julia_plots"
DIST = SITE / "dist"
REPOSITORY = "https://github.com/SSuzukiLab/AkaghefTopology"
PUBLISHED_ARTIFACTS = (
    Path("topology/Manifold/VLExample/figure_002_trefoil.svg"),
    Path("topology/Manifold/VLExample/figure_006_hopf.svg"),
    Path("topology/Manifold/VLExample/figure_007_borromean.svg"),
)


def display_name(path: Path) -> str:
    stem = re.sub(r"^figure_\d+_?", "", path.stem)
    return stem.replace("_", " ").strip().title() or path.stem


def source_name(relative: Path) -> str:
    return " / ".join(relative.parent.parts)


def build() -> int:
    svg_files = [SOURCE / relative for relative in PUBLISHED_ARTIFACTS]
    missing_sources = [path for path in svg_files if not path.is_file()]
    if missing_sources:
        raise SystemExit(f"Missing Julia SVG artifacts: {missing_sources}")

    if DIST.exists():
        shutil.rmtree(DIST)
    (DIST / "plots").mkdir(parents=True)

    groups: dict[Path, list[Path]] = {}
    for source in svg_files:
        relative = source.relative_to(SOURCE)
        destination = DIST / "plots" / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        groups.setdefault(relative.parent, []).append(relative)

    sections = []
    for group, plots in groups.items():
        cards = []
        for relative in plots:
            title = html.escape(display_name(relative))
            label = html.escape(relative.as_posix())
            url = "plots/" + relative.as_posix()
            cards.append(
                f'''<figure class="plot-card">
  <a href="{html.escape(url)}" target="_blank" rel="noopener">
    <img src="{html.escape(url)}" alt="{title} o-graph" decoding="async">
  </a>
  <figcaption><strong>{title}</strong><code>{label}</code></figcaption>
</figure>'''
            )
        heading = html.escape(source_name(plots[0]))
        unit = "figure" if len(plots) == 1 else "figures"
        sections.append(
            f'''<section class="collection">
  <div class="collection-heading"><h2>{heading}</h2><span>{len(plots)} {unit}</span></div>
  <div class="plot-grid">{"".join(cards)}</div>
</section>'''
        )

    page = f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Topology.jl workbench: reproducible Julia-generated o-graph artifacts.">
  <title>Topology.jl Workbench</title>
  <link rel="stylesheet" href="site.css">
</head>
<body>
  <header class="hero">
    <nav><a class="brand" href="#top">Topology.jl</a><a href="#gallery">Gallery</a><a href="{REPOSITORY}/tree/master/julia">Source</a></nav>
    <div class="hero-copy" id="top">
      <p class="eyebrow">MATHEMATICAL SOFTWARE · JULIA WORKBENCH</p>
      <h1>Topology computations,<br>made inspectable.</h1>
      <p class="lede">A public surface for reproducible o-graph artifacts generated by the in-progress MATLAB-to-Julia migration.</p>
      <div class="actions"><a class="primary" href="#gallery">Browse {len(svg_files)} figures</a><a href="{REPOSITORY}">View repository</a></div>
    </div>
  </header>

  <main>
    <section class="status" aria-label="Project status">
      <div><span>STATUS</span><strong>Migration workbench</strong></div>
      <div><span>RUNTIME</span><strong>Julia 1.6+</strong></div>
      <div><span>PUBLISHED ARTIFACTS</span><strong>{len(svg_files)} SVGs</strong></div>
    </section>

    <section class="notice">
      <h2>Evidence, not final acceptance</h2>
      <p>These files are generated outputs from the implemented Julia subset. They are useful for inspection and comparison, but do not claim complete MATLAB fidelity. Canonical scope and verification status remain in the repository.</p>
      <div class="doc-links">
        <a href="{REPOSITORY}/blob/master/julia/README.md">Workbench README</a>
        <a href="{REPOSITORY}/blob/master/julia/LIVE_SCRIPT_SCOPE.md">Migration scope</a>
        <a href="{REPOSITORY}/blob/master/julia/VISUAL_VERIFICATION.md">Visual verification</a>
      </div>
    </section>

    <section class="gallery-intro" id="gallery">
      <p class="eyebrow">GENERATED OUTPUT</p>
      <h2>O-graph gallery</h2>
      <p>Each image links to the original vector artifact. Paths preserve their source workflow so that documentation stays traceable to computation.</p>
    </section>
    {"".join(sections)}
  </main>

  <footer><p>Generated from <a href="{REPOSITORY}/tree/master/julia">Topology.jl</a> artifacts. The Julia repository remains canonical; this website is a static projection.</p></footer>
</body>
</html>
'''
    (DIST / "index.html").write_text(page, encoding="utf-8")
    shutil.copy2(SITE / "site.css", DIST / "site.css")
    shutil.copy2(SITE / "_headers", DIST / "_headers")
    print(f"Built {len(svg_files)} plots in {len(groups)} collections at {DIST}")
    return len(svg_files)


if __name__ == "__main__":
    build()
