function topology_replay_error(callId, lineNumber, exception)
%TOPOLOGY_REPLAY_ERROR Persist a per-plot failure without aborting the script.

errors = getappdata(groot,"TopologyReplayErrors");
errors(end+1) = struct( ...
    "callId",callId, ...
    "lineNumber",lineNumber, ...
    "identifier",string(exception.identifier), ...
    "message",string(exception.message));
setappdata(groot,"TopologyReplayErrors",errors);
fprintf(2,"PLOT_ERROR call=%d line=%d id=%s message=%s\n", ...
    callId,lineNumber,exception.identifier,exception.message);
end
